--CREATE TABLE PERSON
--(
--    ID INTEGER PRIMARY KEY,
--    NAME VARCHAR(255) NOT NULL,
--    LOCATION VARCHAR(255),
--    BIRTH_DATE TIMESTAMP
--);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10001, 'Nimit', 'Khambha', CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10002, 'Nim', 'Ahmedabad', CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10003, 'MN', 'Surat', CURRENT_TIMESTAMP());